COMP: Manually implement setters of model configurations
Addressed Debug compilation errors from those `itkSetMacro` calls, saying:

    ITK\Modules\Core\Common\include\itkPrintHelper.h(53,10): error C2679: binary '<<': no operator found which takes a right-hand operand of type 'const _Ty' (or there is no acceptable conversion)

Did not make these "set functions" virtual, as they do not need to be overridden. Did not call `itkDebugMacro`.